language: node_js
node_js:
  - "14"
script:
  - npm run lint
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: dist
  fqdn: book.phantom-sea-limited.ltd
  on:
    branch: master
