language: node_js
node_js:
  - "14"
script:
  - npm run lint
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: 56acfa7f1dae8c60be06c497a75f7cf239a1c384
  keep-history: true
  local-dir: dist
  fqdn: book.phantom-sea-limited.ltd
  on:
    branch: gh-pages
