export const thanks: Array<{ name: string, link?: string }> = [
  { name: '神楽坂 立音' },
  { name: 'lgd_小翅膀' },
  { name: '青葉' },
  { name: 'kn' },
  { name: 'F74nk', link: 'https://t.me/F74nk_K' },
  { name: '杨佳文' },
  { name: '不知名的N姓人士就好' },
  { name: '某不愿透露姓名的N性？' },
  { name: '神楽坂 萌绫' },
  { name: 'Butby' },
  { name: '友人♪B' },
  { name: 'NekoCaffeine' },
  { name: 'RainSlide' },
  { name: 'czp', link: 'https://www.hiczp.com' },
  { name: 'kookxiang' },
  { name: '櫻川 紗良' },
  { name: 'Skimige' },
].sort(() => Math.random() - 0.5);
