export const thanks: Array<{ name: string, link?: string }> = [
  { name: '神楽坂 立音' },
  { name: 'lgd_小翅膀' },
  { name: '青葉' },
  { name: 'kn' },
  { name: 'F74nk', link: 'https://t.me/F74nk_K' },
  { name: '杨佳文' },
  { name: '不知名的N姓人士就好' },
  { name: '某不愿透露姓名的N性？' },
  { name: '神楽坂 萌绫' },
  { name: 'Butby' },
  { name: '友人♪B' },
  { name: 'NekoCaffeine' },
  { name: 'RainSlide' },
  { name: 'czp', link: 'https://www.hiczp.com' },
  { name: 'kookxiang' },
  { name: '櫻川 紗良' },
  { name: 'Skimige' },
  { name: 'TExL', link: 'http://texas.penguin-logistics.cn' },
  { name: '路人乙' },
  { name: 'pokemonchw', link: 'https://github.com/pokemonchw' },
  { name: '帕蒂卡', link: 'https://github.com/Patika-ailemait' },
  { name: '零件', link: 'https://nekosc.com' },
  { name: '幻梦', link: 'https://t.me/HuanmengQwQ' },
  { name: 'acted咕咕喵', link: 'https://acted.gitlab.io' },
  { name: '重水时雨', link: 'https://t.me/boatmasteronD2O' },
  { name: '神楽坂 紫' },
  { name: 'Runian Lee', link: 'https://t.me/Runian' },
].sort(() => Math.random() - 0.5);
